/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/recipes` | `/recipes`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/like` | `/like`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my` | `/my`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/home/[ingredientId]` | `/home/[ingredientId]`, params: Router.UnknownInputParams & { ingredientId: string | number; } } | { pathname: `${'/(tabs)'}/recipes/[id]` | `/recipes/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/recipes` | `/recipes`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/like` | `/like`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my` | `/my`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(tabs)'}/home/[ingredientId]` | `/home/[ingredientId]`, params: Router.UnknownOutputParams & { ingredientId: string; } } | { pathname: `${'/(tabs)'}/recipes/[id]` | `/recipes/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/recipes${`?${string}` | `#${string}` | ''}` | `/recipes${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/like${`?${string}` | `#${string}` | ''}` | `/like${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my${`?${string}` | `#${string}` | ''}` | `/my${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/recipes` | `/recipes`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/like` | `/like`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my` | `/my`; params?: Router.UnknownInputParams; } | `/+not-found` | `${'/(tabs)'}/home/${Router.SingleRoutePart<T>}` | `/home/${Router.SingleRoutePart<T>}` | `${'/(tabs)'}/recipes/${Router.SingleRoutePart<T>}` | `/recipes/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/home/[ingredientId]` | `/home/[ingredientId]`, params: Router.UnknownInputParams & { ingredientId: string | number; } } | { pathname: `${'/(tabs)'}/recipes/[id]` | `/recipes/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
